name: Test Workflow

on:
  workflow_dispatch:

jobs:
  run-install-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run install.ps1
        shell: pwsh
        run: .\install.ps1

      - name: Check config
        shell: pwsh
        run: scoop config

      - name: Check bucket
        shell: pwsh
        run: scoop bucket list

      - name: Check installed apps
        shell: pwsh
        run: scoop list
